@startuml Map Phase

CLI -> Master: User creates new job
Master -> CLI: Approves data
CLI -> Master: Uploads input data and code

loop Map Task Exists
    Master -> Node: Sends task with map job
    Node --> Worker: Starts executable / python
    Worker -> Node: Requests job data
    Node -> Worker: Returns chunk
    Worker -> Node: Sends results of map operation
    Node -> Master: Sends results of map operation
end

Master -> Master: Map results are sorted

@enduml