@startuml Map Phase

loop Map Task Exists
    Master -> Node: Sends task with map job
    Node --> Worker: Starts executable / python
    Worker -> Node: Requests job data
    Node -> Worker: Returns chunk
    Worker -> Node: Sends results of map operation
    Node -> Master: Sends results of map operation
end

@enduml