# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import internal_pb2 as internal__pb2


class MasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class MasterServicer(object):
  # missing associated documentation comment in .proto file
  pass


def add_MasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mapreduce.Master', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class NodeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartJob = channel.unary_unary(
        '/mapreduce.Node/StartJob',
        request_serializer=internal__pb2.Job.SerializeToString,
        response_deserializer=internal__pb2.Empty.FromString,
        )
    self.GetJob = channel.unary_unary(
        '/mapreduce.Node/GetJob',
        request_serializer=internal__pb2.JobRequest.SerializeToString,
        response_deserializer=internal__pb2.Job.FromString,
        )


class NodeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartJob': grpc.unary_unary_rpc_method_handler(
          servicer.StartJob,
          request_deserializer=internal__pb2.Job.FromString,
          response_serializer=internal__pb2.Empty.SerializeToString,
      ),
      'GetJob': grpc.unary_unary_rpc_method_handler(
          servicer.GetJob,
          request_deserializer=internal__pb2.JobRequest.FromString,
          response_serializer=internal__pb2.Job.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mapreduce.Node', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class WorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass


def add_WorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mapreduce.Worker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
